config/routes.rb
Rails.application.routes.draw do
  root 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :flat_picture, presence: true
  validates :price_per_night, inclusion: { in: 10..10_000 }
  validates :number_of_guests, inclusion: { in: 1..30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @flats = Flat.where("name LIKE ?", "%#{params[:query].downcase}%")
    else
      @flats = Flat.all
    end
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to @flat
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to @flat
    else
      render 'edit'
    end
  end

  def destroy
    @flat.destroy
    redirect_to root_path
  end

  private

  def find_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat)
          .permit(:name, :address, :description, :price_per_night,
                  :number_of_guests, :flat_picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container mt-4">
  <div class="row col-6 m-auto">
    <div class="flat-form  w-100">
      <h1>Add a new Flat</h1>
      <div class="mt-3">
        <%= simple_form_for @flat do |f| %>
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :flat_picture %>
          <%= f.input :description %>
          <input type="range" name="flat[price_per_night]" id="flat_price_per_night" value="125" min="1" max="250" oninput="priceOutputId.value = flat_price_per_night.value">
          <output name="priceOutput" id="priceOutputId">125</output>€
          <%= f.input :number_of_guests, collection: 1..5 %>
          <%= f.submit 'Edit Flat', class: "btn btn-primary" %>
          <%= link_to 'Cancel', flat_path(@flat), class: "btn btn-danger ml-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container p-4">
  <div class="row">
    <div class="index-head">
      <h1>All our Flats</h1>
      <p>All <%= @flats.count %> flats.</p>
    </div>
  </div>

  <div class="row">
    <div class="flat-cards">
      <% @flats.each do |flat| %>
        <div class="flat-card shadow">
          <img src="<%= flat.flat_picture %>" alt="flat picture">
          <div class="flat-card-content">
            <div class="flat-card-title">
              <h4><%= flat.name %></h4>
              <p><%= flat.address %></p>
            </div>

            <div class="flat-card-numbers">
              <i class="fas fa-user-friends mr-1"></i>
              <%= flat.number_of_guests %>
              <i class="fas fa-euro-sign ml-4 mr-1"></i>
              <%= flat.price_per_night %>
            </div>
          </div>

          <div class="flat-card-bottom">
            <%= link_to 'More info', flat_path(flat)%>
            <%= link_to 'Edit', edit_flat_path(flat), class: 'text-warning' %>
            <%= link_to 'Remove', flat_path(flat),
                         method: :delete,
                         data: { confirm: 'Are you sure?' },
                         class: 'text-danger' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-4">
  <div class="row col-6 m-auto">
    <div class="flat-form shadow-sm w-100">
      <h1>Add a new Flat</h1>
      <div class="mt-3">
        <%= simple_form_for @flat do |f| %>
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :flat_picture %>
          <%= f.input :description %>
          <input type="range" name="flat[price_per_night]" id="flat_price_per_night" value="125" min="1" max="250" oninput="priceOutputId.value = flat_price_per_night.value">
          <output name="priceOutput" id="priceOutputId">125</output>€
          <%= f.input :number_of_guests, collection: 1..5 %>
          <%= f.submit 'Create Flat', class: "btn btn-primary" %>
          <%= link_to 'Cancel', flats_path, class: "btn btn-danger ml-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="main-img" style="background-image: url(<%= @flat.flat_picture %>)">
</div>

<div class="container p-4" id="background-overflow">
  <div class="row">
    <div class="col-8">
      <div class="details-card">
        <div class="details-card-header shadow-sm">
          <h1><%= @flat.name %></h1>
          <p><%= @flat.address %></p>
        </div>

        <div class="details-card-info shadow-sm">
          <h3>A bit more about this flat...</h3>
          <span style="white-space: pre-line"><%= @flat.description %></span>
        </div>
      </div>
    </div>

    <div class="col-4">
      <div class="rental-card">
        <div class="rental-card-calendar shadow-sm">
          <h5>Book this place!</h5>
          <form>
            <div class="input-group mb-2">
              <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">From:</span>
              </div>
              <input type="text" class="form-control" placeholder="dd/mm/yyyy" aria-label="rental-start-date" aria-describedby="basic-addon1">
            </div>
            <div class="input-group mb-2">
              <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">To:</span>
              </div>
              <input type="text" class="form-control" placeholder="dd/mm/yyyy" aria-label="rental-end-date" aria-describedby="basic-addon1">
            </div>
            <button type="submit" class="btn btn-success w-100">Book</button>
          </form>
        </div>

        <div class="rental-card-numbers shadow-sm">
          <h3>Details</h3>
          <div class="flat-card-numbers">
            <i class="fas fa-user-friends mr-1"></i>
            <%= @flat.number_of_guests %>
            <i class="fas fa-euro-sign ml-4 mr-1"></i>
            <%= @flat.price_per_night %>
          </div>
        </div>

        <div class="rental-card-social shadow-sm">
          <h6>Share</h6>
          <div class="social-icons">
            <i class="fab fa-facebook-square"></i>
            <i class="fab fa-twitter-square"></i>
            <i class="fab fa-pinterest-square"></i>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnbReboot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
  <div class="navbar-left">
    <%= link_to 'Simple Airbnb', root_path, class: 'navbar-brand' %>
  </div>

  <div class="navbar-right d-flex">
    <%= form_tag root_path, method: :get, class: "search-bar form-inline" do %>
      <div class="input-area">
        <%= text_field_tag :query,
          params[:query],
          class: "form-control mr-1",
          placeholder: "Search for a flat"
        %>
        <%= submit_tag "Search", class: "btn btn-outline-success" %>
      </div>
    <% end %>

    <%= link_to 'Add Flat', new_flat_path, class: 'btn btn-outline-primary ml-2' %>
  </div>
</nav>